### ISSUE TITLE
remove /b/ between server and room-id-from-greenlight

### ISSUE THREAD

**Issue by jeau** [lukas2511/bbb-streaming#2]
Thank you for your work

to access my server I don't have `/b/ `between my bbb server address and the room id from greenlight. 
bbb-streaming can't connect because it rebuilds the url with this `/b/` (it's `gl`in my case, see example below)

The error message:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/stream/test.py", line 15, in <module>
    join_url = session.greenlight_join(sys.argv[1], sys.argv[2])
  File "/opt/stream/lib/session.py", line 17, in greenlight_join
    authenticity_token = session.get("https://" + server + "/b/" + room).text.split('name="authenticity_token"')[1].split('"')[1]
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //demo.bigbluebutton.org/gl//b/thi-mqt-cqa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2fcb4e59a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Jeau

**Comment by lukas2511** [comment]
Please patch this for yourself for now. I'll add a lot more options about how to enter rooms etc. in the near future, for now that's just test code to get it to somehow join a server.
