### ISSUE TITLE
Stream only with audio and background image

### ISSUE THREAD

**Issue by roere** [lukas2511/bbb-streaming#6]
Hi,
tried to stream a BBB Session with the following command:

`docker run -t -i --rm=true lukas2511/bbb-streaming --greenlight-url https://meet.piratensommer.de/b/xxx-xxx-xxx-xxx --greenlight-name stream --rtmp-url rtmp://example.de:1935/live/xxxxxxxxx --debug`

The RTMP Stream is reaching my plattform with audio and a (standard?) backround image but without the video. Am I doing something wrong?

INFO:bbb-streamer:Joining using Greenlight frontend
DEBUG:bbb-streamer:Trying to acquire join url from greenlight: https://meet.piratensommer.de/b/xxx-xxx-xxx-xxx (without access code)
DEBUG:bbb-streamer:Got join url: https://meet.piratensommer.de/bigbluebutton/api/join?...
INFO:bbb-streamer:Found STUN server: stun.freeswitch.org
DEBUG:bbb-streamer:Connecting to websocket
DEBUG:bbb-streamer:Sending initial control messages
DEBUG:bbb-streamer:Subscribing to annotations messages
DEBUG:bbb-streamer:Subscribing to current-user messages
DEBUG:bbb-streamer:Subscribing to group-chat messages
DEBUG:bbb-streamer:Subscribing to group-chat-msg messages
DEBUG:bbb-streamer:Subscribing to guestUser messages
DEBUG:bbb-streamer:Subscribing to local-settings messages
DEBUG:bbb-streamer:Subscribing to meetings messages
DEBUG:bbb-streamer:Subscribing to network-information messages
DEBUG:bbb-streamer:Subscribing to note messages
DEBUG:bbb-streamer:Subscribing to ping-pong messages
DEBUG:bbb-streamer:Subscribing to presentations messages
DEBUG:bbb-streamer:Subscribing to screenshare messages
DEBUG:bbb-streamer:Subscribing to slide-positions messages
DEBUG:bbb-streamer:Subscribing to slides messages
DEBUG:bbb-streamer:Subscribing to users messages
DEBUG:bbb-streamer:Subscribing to users-infos messages
DEBUG:bbb-streamer:Subscribing to video-streams messages
DEBUG:bbb-streamer:Subscribing to voice-call-states messages
DEBUG:bbb-streamer:Subscribing to voiceUsers messages
DEBUG:bbb-streamer:Session manager is ready
DEBUG:bbb-streamer:Initializing audio connection
DEBUG:bbb-streamer:Attaching listener to session manager: <bound method CameraManager.listener of <lib.camera.CameraManager object at 0x7f2314269520>>
DEBUG:bbb-streamer:Connecting to bbb-webrtc-sfu
DEBUG:bbb-streamer:Attaching listener to session manager: <bound method Presentation.listener of <lib.presentation.Presentation object at 0x7f2314269730>>
DEBUG:bbb-streamer:Attaching listener to session manager: <bound method ScreenshareManager.listener of <lib.screenshare.ScreenshareManager object at 0x7f23141b5940>>
DEBUG:bbb-streamer:Attaching listener to session manager: <function start.<locals>.chatmsg at 0x7f23141b45e0>
(bbb) DEBUG:bbb-streamer:Starting audio webrtc pipeline
INFO:bbb-streamer:Sending offer for audio
DEBUG:bbb-streamer:Fixing sdp offer, broken opus codec line: a=rtpmap:111 opus/48000
DEBUG:bbb-streamer:Sending audio SDP offer: 'v=0\r\no=- 1236737925857283059 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=ice-options:trickle\r\na=group:BUNDLE audio0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 0.0.0.0\r\na=setup:actpass\r\na=ice-ufrag:HVioQASYnwRZotieCvmN7EkQQlKO9i/W\r\na=ice-pwd:BaFMNwibUYtZ3bDlDviFwXIETqhFE895\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=recvonly\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 nack pli\r\na=fmtp:111 fec-type=ulp-red\r\na=mid:audio0\r\na=fingerprint:sha-256 06:D5:23:2A:33:5E:7A:CD:85:8E:AF:3A:06:A4:44:90:FE:7E:2F:BB:94:DF:82:FA:86:62:6D:74:09:BB:6A:E0'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/stream/lib/session.py", line 94, in run
    listener(msg)
  File "/opt/stream/lib/camera.py", line 68, in listener
    self.voice_users[msg['id']].update(msg['fields'])
KeyError: 'GKGGh84eh9gfcT4Yj'
INFO:bbb-streamer:WebRTC <Audio(Thread-6, started daemon 139787084228160)> ready

**Comment by lukas2511** [comment]
I've noticed some issues with newer BBB versions and I'll have to update this script to deal with that. Unfortunately didn't find the time to do that yet.
